// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cehgsygfwkomthauwvgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlaGdzeWdmd2tvbXRoYXV3dmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDI1MzIsImV4cCI6MjA2NjQxODUzMn0.5-O4gkz3S0K_8vRg-hoiVF1wEn_Cct0nT-8DGvF74DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);